# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'safeSpot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for safeSpot
source 'https://github.com/MapQuest/podspecs-ios.git'
pod 'MapQuestMaps', '~> 3.2.1-1.3'
end
