# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'safeSpot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for safeSpot
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Lock', '~> 1.26'
pod 'Auth0', '1.0.0-beta.5'
end
